name: project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - shap=0.47.2
  - jupyterlab
